### ISSUE TITLE
quick.db showing error

### ISSUE THREAD

**Issue by Rayne231** [lorencerri/quick.db#174]
**Expected behavior**
run without error

**Screenshots**
getting this error 
```js
C:\Users\..\Desktop\AvaBot>npm i quick.db
+ quick.db@7.1.1
updated 1 package and audited 340 packages in 10.753s

18 packages are looking for funding
  run `npm fund` for details

found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

C:\Users\..\Desktop\AvaBot>npm audit

                       === npm audit security report ===                        


                                 Manual Review                                  
             Some vulnerabilities require your attention to resolve             
                                                                                
          Visit https://go.npm.me/audit-guide for additional guidance           


  Low             Prototype Pollution                                           

  Package         lodash                                                        

  Patched in      >=4.17.19                                                     

  Dependency of   quick.db                                                      

  Path            quick.db > lodash                                             

  More info       https://npmjs.com/advisories/1523                             

found 1 low severity vulnerability in 340 scanned packages
  1 vulnerability requires manual review. See the full report for details.```

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser chrome

**Comment by Rayne231** [comment]
```js
C:\Users\..\Desktop\AvaBot\node_modules\bindings\bindings.js:135
  throw err;
  ^

Error: Could not locate the bindings file. Tried:
 → C:\Users\..\Desktop\AvaBot\node_modules\better-sqlite3\build\better_sqlite3.node
 → C:\Users\..\Desktop\AvaBot\node_modules\better-sqlite3\build\Debug\better_sqlite3.node
 → C:\Users\..\Desktop\AvaBot\node_modules\better-sqlite3\build\Release\better_sqlite3.node
 → C:\Users\..\Desktop\AvaBot\node_modules\better-sqlite3\out\Debug\better_sqlite3.node
 → C:\Users\..\Desktop\AvaBot\node_modules\better-sqlite3\Debug\better_sqlite3.node
 → C:\Users\..\Desktop\AvaBot\node_modules\better-sqlite3\out\Release\better_sqlite3.node
 → C:\Users\..\Desktop\AvaBot\node_modules\better-sqlite3\Release\better_sqlite3.node
 → C:\Users\..\Desktop\AvaBot\node_modules\better-sqlite3\build\default\better_sqlite3.node
 → C:\Users\..\Desktop\AvaBot\node_modules\better-sqlite3\compiled\12.18.3\win32\x64\better_sqlite3.node
 → C:\Users\..\Desktop\AvaBot\node_modules\better-sqlite3\addon-build\release\install-root\better_sqlite3.node
 → C:\Users\..\Desktop\AvaBot\node_modules\better-sqlite3\addon-build\debug\install-root\better_sqlite3.node
 → C:\Users\..\Desktop\AvaBot\node_modules\better-sqlite3\addon-build\default\install-root\better_sqlite3.node
 → C:\Users\..\Desktop\AvaBot\node_modules\better-sqlite3\lib\binding\node-v72-win32-x64\better_sqlite3.node
    at bindings (C:\Users\..Desktop\AvaBot\node_modules\bindings\bindings.js:126:9)
    at Object.<anonymous> (C:\Users\..\Desktop\AvaBot\node_modules\better-sqlite3\lib\database.js:6:40)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\..\Desktop\AvaBot\node_modules\better-sqlite3\lib\index.js:2:18)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\..\Desktop\AvaBot\node_modules\quick.db\bin\handler.js:2:18) {
  tries: [
    'C:\\Users\\..\\Desktop\\AvaBot\\node_modules\\better-sqlite3\\build\\better_sqlite3.node',
    'C:\\Users\\..\\Desktop\\AvaBot\\node_modules\\better-sqlite3\\build\\Debug\\better_sqlite3.node',
    'C:\\Users\\..\Desktop\\AvaBot\\node_modules\\better-sqlite3\\build\\Release\\better_sqlite3.node',
    'C:\\Users\\..\\Desktop\\AvaBot\\node_modules\\better-sqlite3\\out\\Debug\\better_sqlite3.node',
    'C:\\Users\\..\\Desktop\\AvaBot\\node_modules\\better-sqlite3\\Debug\\better_sqlite3.node',
    'C:\\Users\\..\\Desktop\\AvaBot\\node_modules\\better-sqlite3\\out\\Release\\better_sqlite3.node',
    'C:\\Users\\..\\Desktop\\AvaBot\\node_modules\\better-sqlite3\\Release\\better_sqlite3.node',
    'C:\\Users\\.\\Desktop\\AvaBot\\node_modules\\better-sqlite3\\build\\default\\better_sqlite3.node',
    'C:\\Users\\..\\Desktop\\AvaBot\\node_modules\\better-sqlite3\\compiled\\12.18.3\\win32\\x64\\better_sqlite3.node',    'C:\\Users\\..\\Desktop\\AvaBot\\node_modules\\better-sqlite3\\addon-build\\release\\install-root\\better_sqlite3.node',
    'C:\\Users\\..\\Desktop\\AvaBot\\node_modules\\better-sqlite3\\addon-build\\debug\\install-root\\better_sqlite3.node',
    'C:\\Users\\..\\Desktop\\AvaBot\\node_modules\\better-sqlite3\\addon-build\\default\\install-root\\better_sqlite3.node',
    'C:\\Users\\..\\Desktop\\AvaBot\\node_modules\\better-sqlite3\\lib\\binding\\node-v72-win32-x64\\better_sqlite3.node'
  ]
}```

**Comment by Rayne231** [comment]
i have also trued running `npm audit fix`

**Comment by rhld16** [comment]
lodash has since been bumped in this repo
