### ISSUE TITLE
Error: Could not locate the bindings file. Tried:

### ISSUE THREAD

**Issue by fozenistaken** [lorencerri/quick.db#193]
/rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/bindings/1.5.0/node_modules/bindings/bindings.js:135
  throw err;
  ^
Error: Could not locate the bindings file. Tried:
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/build/better_sqlite3.node
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/build/Debug/better_sqlite3.node
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/build/Release/better_sqlite3.node
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/out/Debug/better_sqlite3.node
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/Debug/better_sqlite3.node
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/out/Release/better_sqlite3.node
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/Release/better_sqlite3.node
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/build/default/better_sqlite3.node
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/compiled/12.0.0/linux/x64/better_sqlite3.node
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/addon-build/release/install-root/better_sqlite3.node
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/addon-build/debug/install-root/better_sqlite3.node
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/addon-build/default/install-root/better_sqlite3.node
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/lib/binding/node-v72-linux-x64/better_sqlite3.node
    at bindings (/rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/bindings/1.5.0/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/lib/database.js:9:24)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/lib/index.js:2:18)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
/rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/bindings/1.5.0/node_modules/bindings/bindings.js:135
  throw err;
  ^
Error: Could not locate the bindings file. Tried:
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/build/better_sqlite3.node
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/build/Debug/better_sqlite3.node
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/build/Release/better_sqlite3.node
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/out/Debug/better_sqlite3.node
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/Debug/better_sqlite3.node
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/out/Release/better_sqlite3.node
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/Release/better_sqlite3.node
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/build/default/better_sqlite3.node
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/compiled/12.0.0/linux/x64/better_sqlite3.node
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/addon-build/release/install-root/better_sqlite3.node
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/addon-build/debug/install-root/better_sqlite3.node
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/addon-build/default/install-root/better_sqlite3.node
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/lib/binding/node-v72-linux-x64/better_sqlite3.node
    at bindings (/rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/bindings/1.5.0/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/lib/database.js:9:24)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/lib/index.js:2:18)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
/rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/bindings/1.5.0/node_modules/bindings/bindings.js:135
  throw err;
  ^
Error: Could not locate the bindings file. Tried:
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/build/better_sqlite3.node
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/build/Debug/better_sqlite3.node
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/build/Release/better_sqlite3.node
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/out/Debug/better_sqlite3.node
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/Debug/better_sqlite3.node
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/out/Release/better_sqlite3.node
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/Release/better_sqlite3.node
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/build/default/better_sqlite3.node
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/compiled/12.0.0/linux/x64/better_sqlite3.node
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/addon-build/release/install-root/better_sqlite3.node
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/addon-build/debug/install-root/better_sqlite3.node
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/addon-build/default/install-root/better_sqlite3.node
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/lib/binding/node-v72-linux-x64/better_sqlite3.node
    at bindings (/rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/bindings/1.5.0/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/lib/database.js:9:24)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/lib/index.js:2:18)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
/rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/bindings/1.5.0/node_modules/bindings/bindings.js:135
  throw err;
  ^
Error: Could not locate the bindings file. Tried:
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/build/better_sqlite3.node
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/build/Debug/better_sqlite3.node
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/build/Release/better_sqlite3.node
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/out/Debug/better_sqlite3.node
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/Debug/better_sqlite3.node
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/out/Release/better_sqlite3.node
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/Release/better_sqlite3.node
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/build/default/better_sqlite3.node
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/compiled/12.0.0/linux/x64/better_sqlite3.node
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/addon-build/release/install-root/better_sqlite3.node
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/addon-build/debug/install-root/better_sqlite3.node
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/addon-build/default/install-root/better_sqlite3.node
 → /rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/lib/binding/node-v72-linux-x64/better_sqlite3.node
    at bindings (/rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/bindings/1.5.0/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/lib/database.js:9:24)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/rbd/pnpm-volume/92846990-5035-44e5-9b20-1c5a95a6b026/node_modules/.registry.npmjs.org/better-sqlite3/7.1.1/node_modules/better-sqlite3/lib/index.js:2:18)
    at Module._compile (internal/modules/cjs/loader.js:759:30)

**Comment by PatheticMustan** [comment]
I have the same error, when installing quick.db, it either stalls forever until I manually quit, or throws errors about not having the binding file

**Comment by lorencerri** [comment]
> I have the same error, when installing quick.db, it either stalls forever until I manually quit, or throws errors about not having the binding file

Hello, have you tried these steps to help solve your installation issues? https://github.com/JoshuaWise/better-sqlite3/blob/master/docs/troubleshooting.md

**Comment by PatheticMustan** [comment]
alright, so the issue seems to be solely better-sqlite3. I tried all the steps, and looked around the issue tracker.
There's https://github.com/JoshuaWise/better-sqlite3/issues/541, but none of the maintainers have responded yet....

**Comment by Natemo6348** [comment]
I have this same error, the only way I've ever fixed it before is `npm rebuild better-sqlite3` which took a couple of tries, not working now

**Comment by ArchVision** [comment]
Yeah I have this same error, I have never had this up until recently... My error is similar, something with splite-3, can't access the path. I hope there is a fix soon.
