### ISSUE TITLE
Quick.db Not Installing (macOS) Node 14

### ISSUE THREAD

**Issue by Lucaslah** [lorencerri/quick.db#197]
**Describe the bug**
When I attempt to Install quick.db `npm i quick.db` on macOS the Install fails.

**To Reproduce**
1. Install `node-gyp` (`npm i node-gyp`)
2. Install `quick.db` (`npm i quick.db`)
3. On macOS the Install fails 

**Expected behavior**
Quick.db should Install

**Error**
When Installing it get this error:
```

> better-sqlite3@7.1.1 install /Volumes/user/Files/WE-BT16/WE-BT16-Discord-Bot/node_modules/better-sqlite3
> prebuild-install || npm run build-release

prebuild-install WARN install No prebuilt binaries found (target=14.9.0 runtime=node arch=x64 libc= platform=darwin)

> better-sqlite3@7.1.1 build-release /Volumes/Lucas's HHD/Files/WE-BT16/WE-BT16-Discord-Bot/node_modules/better-sqlite3
> node-gyp rebuild --release

  TOUCH b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
  ACTION deps_sqlite3_gyp_locate_sqlite3_target_extract_sqlite3 b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
/bin/sh: -c: line 0: unexpected EOF while looking for matching `"'
/bin/sh: -c: line 1: syntax error: unexpected end of file
make: *** [b857c92884e9598d609f6be182a2595df7a8e00f.intermediate] Error 2
rm b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /Volumes/user/Files/WE-BT16/WE-BT16-Discord-Bot/node_modules/better-sqlite3
gyp ERR! node -v v14.9.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! better-sqlite3@7.1.1 build-release: `node-gyp rebuild --release`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the better-sqlite3@7.1.1 build-release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2020-12-19T03_47_37_983Z-debug.log
npm WARN discord.js-commando@0.10.0 requires a peer of discord.js@^11.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js-commando@0.10.0 requires a peer of sqlite@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN we-bt16@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! better-sqlite3@7.1.1 install: `prebuild-install || npm run build-release`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the better-sqlite3@7.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2020-12-19T03_47_38_680Z-debug.log
```

**Desktop**
 - OS: macOS 10.14
 - Node Version: v14.9.0

**Additional context**
N/A

**Comment by Lucaslah** [comment]
I fixed the issue

**Comment by Zayelion** [comment]
@Lucaslah how did you end up fixing the issue?

**Comment by Lucaslah** [comment]
@Zayelion I did `npm i better-sqlite3` then `npm i quick.db` then It installed
