### ISSUE TITLE
Quick.db is not installed

### ISSUE THREAD

**Issue by GproGamer12** [lorencerri/quick.db#216]
412 error code 1
413 error path C:\Users\jesus_000\Desktop\122\node_modules\better-sqlite3
414 error command failed
415 error command C:\Windows\system32\cmd.exe /d /s /c prebuild-install || npm run build-release
416 error > better-sqlite3@7.4.3 build-release
416 error > node-gyp rebuild --release
417 error prebuild-install WARN install No prebuilt binaries found (target=16.9.1 runtime=node arch=ia32 libc= platform=win32)
417 error gyp info it worked if it ends with ok
417 error gyp info using node-gyp@7.1.2
417 error gyp info using node@16.9.1 | win32 | ia32
417 error gyp info find Python using Python version 3.9.7 found at "C:\Users\jesus_000\AppData\Local\Programs\Python\Python39-32\python.exe"
417 error gyp ERR! find VS
417 error gyp ERR! find VS msvs_version was set from command line or npm config
417 error gyp ERR! find VS - looking for Visual Studio version 2019
417 error gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
417 error gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
417 error gyp ERR! find VS looking for Visual Studio 2015
417 error gyp ERR! find VS - not found
417 error gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
417 error gyp ERR! find VS
417 error gyp ERR! find VS valid versions for msvs_version:
417 error gyp ERR! find VS
417 error gyp ERR! find VS **************************************************************
417 error gyp ERR! find VS You need to install the latest version of Visual Studio
417 error gyp ERR! find VS including the "Desktop development with C++" workload.
417 error gyp ERR! find VS For more information consult the documentation at:
417 error gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
417 error gyp ERR! find VS **************************************************************
417 error gyp ERR! find VS
417 error gyp ERR! configure error
417 error gyp ERR! stack Error: Could not find any Visual Studio installation to use
417 error gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\jesus_000\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
417 error gyp ERR! stack     at C:\Users\jesus_000\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
417 error gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\jesus_000\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
417 error gyp ERR! stack     at C:\Users\jesus_000\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
417 error gyp ERR! stack     at C:\Users\jesus_000\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
417 error gyp ERR! stack     at C:\Users\jesus_000\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
417 error gyp ERR! stack     at C:\Users\jesus_000\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
417 error gyp ERR! stack     at ChildProcess.exithandler (node:child_process:404:5)
417 error gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
417 error gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
417 error gyp ERR! System Windows_NT 6.3.9600
417 error gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\jesus_000\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
417 error gyp ERR! cwd C:\Users\jesus_000\Desktop\122\node_modules\better-sqlite3
417 error gyp ERR! node -v v16.9.1
417 error gyp ERR! node-gyp -v v7.1.2
417 error gyp ERR! not ok
418 verbose exit 1

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
I have already done everything possible to try to improve, I have installed vs_2015, 17, 19. different versions of python and nothing, there are no more ways to try to run npm. My system is windows 8.1, x86 architecture.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by Zelak312** [comment]
Like cryptosbyte said, you are missing "Visual C++ build tools" which can be installed with Visual Studio or manually.
You can find these steps in the [better-sqlite3 troubleshooting guide](https://github.com/JoshuaWise/better-sqlite3/blob/master/docs/troubleshooting.md)
